language: node_js
node_js:
  - "8.12"
sudo: false
env:
  - NODE_ENV='test'
script:
  - yarn install
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      sudo: required
      node_js: false
      before_install:
        - openssl aes-256-cbc -K $encrypted_81656b5e166a_key -iv $encrypted_81656b5e166a_iv -in secrets.tar.enc -out secrets.tar -d
        - tar xvf secrets.tar
        - nvm install node
        - node --version
        - travis_retry curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - travis_retry sudo apt-get update -qq
        - travis_retry sudo apt-get install -y -qq yarn
      install:
        - yarn install --frozen-lockfile
      deploy:
        provider: releases
        api_key:
          secure: PAOPhK4V3QcD9xwe7doux5wbZBQ+9yI1PPVxEROKVL9F3ploddiXCCTteYrZRX3X/lwi0RshKZlLifPVwZNgnnLAMXpua/q5RWafiIN2HCT7u+Etju0baaLzXIzhh2ZLeDWfWf9y/na65Q1Ys4nZ9Fo4CiiZ5sqbLbb6pBhZrM7USc4+Ec8M8Av0kqULpDYfP16k2dOyyMhAbxz5boD6SWng3DY4bwygag5yL03UkqwsOssLYS4JtYeuandxPExb+R56JhI/mbiTyijoNYtIi/cPNkFm8S1DrLmcqrdFuF1i/F7GSRvu5pS7tXKWR9hAeXJDpCEAqRSJys80OLn3jy2n0ym93eYCXNtvasJrRy5teyh4d5dwbc9c5mEHjAJe+ftnyHkQGJuax1fJZCdnW3oGZam6H6/rpAcjtJ2bzmmeyk0Be9N2iYFlReMqrxwMUtCYcFzZSn9c39GNnyYzCDZwuRDUPn564i+JdaG5hsW16TY51pSHspuNT4nZLSCGpSbViLb2547L9sNyzqQmX8GYdE5/6lILdVX4SJJj5ihgyeMkP1ghsg8Gj4LD1OVxQTtOUWZ5LPT61kAfyz6F0GygYN+oiLev3KxGBm4EzrNmOgUChEAnA24+BKk25nnaHUBJqwoOXl2SczWjUDU8jAocr+Kt28yl+67ZrsL3U/o=
        file: android/app/build/outputs/apk/dev/debug/app-dev-debug.apk
        skip_cleanup: true
        on:
          all_branches: true
          repo: laurentS/mapswipe
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.2
          - android-28
          - android-27
          - android-26
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-27
      script:
        - yarn buildDev
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      node_js: false
      before_install:
        - nvm install node
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
        - wget -nv https://dl.google.com/firebase/sdk/ios/5_12_0/Firebase-5.12.0.zip
        - unzip -q Firebase-5.12.0.zip -d ios
      install:
        - travis_retry gem install xcpretty cocoapods
        - travis_retry yarn install --frozen-lockfile
      xcode_project: ios/mapswipe.xcworkspace
      xcode_scheme: ios/mapswipeTests
      script:
        - cd ios
        - pod install
        - xcodebuild -scheme mapswipe -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
        - travis_retry xctool run-tests -scheme mapswipe -sdk iphonesimulator -launch-timeout 90  ONLY_ACTIVE_ARCH=NO
